version: "3.8"


networks:
  internal:
    driver: bridge

  shared:
    external: true
    name: shopy-shared-net

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: shopy-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - shared
      - internal

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: shopy-kafka
    depends_on:
      - zookeeper
    ports:
      - "9097:9092"
    environment:
      KAFKA_BROKER_ID: 1

      # INTERNAL listener for communication *inside Docker* between services
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Zookeeper connection
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CFG_LOG_RETENTION_MS: 260000000

    networks:
      - shared
      - internal
