spring:
  grpc:
    server:
      port: 2030
      reflection:
        enabled: true
  kafka:
    bootstrap-servers: kafka:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false

    consumer:
      group-id: shopy-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
        spring.json.value.default.type: org.radon.shopyorder.events.domain.model.UserRegisteredEvent