spring.application.name=Shopy


spring.datasource.url=jdbc:postgresql://postgres:5432/shopy-db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.data.redis.host=redis
spring.data.redis.port=6379

spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Automatically update schema (optional)
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in logs (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always

# Redis configs
spring.data.redis.timeout=5000ms
spring.data.redis.lettuce.shutdown-timeout=100ms

#Performance monitoring with Prometheus + MicroMeter (Actuator) + GraphAna
# --- Management endpoints ---
management.endpoints.web.exposure.include=health,info,prometheus,metrics, httptrace

# --- Basic app info ---
management.info.env.enabled=true
management.endpoint.health.show-details=always

# --- Metrics tags (optional but useful) ---
management.metrics.tags.application=my-spring-app
